### ISSUE TITLE
CREATE A FUNCTION TO DISPLAY PRODUCTS ON THE UI

### ISSUE THREAD

**Issue by LOSTBOY-IS-DED** [LOSTBOY-IS-DED/Shopping_cart_assignment#1]
This function is responsible for displaying the list of products on the webpage. It dynamically creates HTML elements for each product, including its name, price, and an "Add to Cart" button. The products are fetched from an array (products) and appended to the DOM inside the .product-list container.

**Comment by vidyadharcodes** [comment]
I don't know how to use tailwind css . I am trying to do design through style.css
